"""initial_migration

Revision ID: b1cb3bc098ee
Revises:
Create Date: 2026-06-05 14:32:33.441530+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1cb3bc098ee"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "fx_rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate_to_usd", sa.Float(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("currency"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_code", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("manager_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("employee_code"),
    )
    with op.batch_alter_table("employee", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_employee_country"), ["country"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_employee_department_id"), ["department_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_employee_last_name"), ["last_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_employee_level"), ["level"], unique=False)
        batch_op.create_index(batch_op.f("ix_employee_status"), ["status"], unique=False)

    op.create_table(
        "compensation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("base_annual", sa.Integer(), nullable=False),
        sa.Column("bonus_annual", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("compensation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_compensation_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_compensation_is_current"), ["is_current"], unique=False
        )

    op.create_table(
        "salary_change_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salary_change_history")
    with op.batch_alter_table("compensation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_compensation_is_current"))
        batch_op.drop_index(batch_op.f("ix_compensation_employee_id"))

    op.drop_table("compensation")
    with op.batch_alter_table("employee", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employee_status"))
        batch_op.drop_index(batch_op.f("ix_employee_level"))
        batch_op.drop_index(batch_op.f("ix_employee_last_name"))
        batch_op.drop_index(batch_op.f("ix_employee_department_id"))
        batch_op.drop_index(batch_op.f("ix_employee_country"))

    op.drop_table("employee")
    op.drop_table("user")
    op.drop_table("fx_rate")
    op.drop_table("department")
    # ### end Alembic commands ###
