"""add hire_date

Revision ID: 5b5ab69c6a9a
Revises: b1cb3bc098ee
Create Date: 2026-06-07 08:21:54.082875+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5ab69c6a9a'
down_revision: Union[str, None] = 'b1cb3bc098ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=True))
    
    # Set a default value for existing rows
    op.execute("UPDATE employee SET hire_date = '2020-01-01' WHERE hire_date IS NULL")
    
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('hire_date', nullable=False)
        batch_op.create_index(batch_op.f('ix_employee_hire_date'), ['hire_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_hire_date'))
        batch_op.drop_column('hire_date')

    # ### end Alembic commands ###
